### ISSUE TITLE
Error running timer

### ISSUE THREAD

**Issue by oneingan** [protesilaos/dotfiles#3]
Recently I started to have errors while loading your config. Exactly this:

```
Error running timer: (void-function denote-rename-buffer-mode)
Error running timer: (void-variable org-mode-map)
```

Can you help me to debug it? `emacs --debug-init` makes not difference and neither displays trace.

Regards.

**Comment by oneingan** [comment]
Update: `Error running timer: (void-function denote-rename-buffer-mode)` disappear updating denote to elpa-devel

**Comment by protesilaos** [comment]
Yes, the function is part of the latest development version of Denote.

**Comment by oneingan** [comment]
Sure, but I mean, `Error running timer: (void-variable org-mode-map)` still remains, and org-mode configurations are not loaded. Seems like a race condition problem to me. Because if I eval `prot-emacs-org.el` problem is still there, but if I eval first this block
```elisp
(prot-emacs-keybind org-mode-map
    ;; I don't like that Org binds one zillion keys, so if I want one
    ;; for something more important, I disable it from here.
    "C-'" nil
    "C-," nil
    "M-;" nil
    "<C-return>" nil
    "<C-S-return>" nil
    "C-M-S-<right>" nil
    "C-M-S-<left>" nil
    "C-c M-l" #'org-insert-last-stored-link
    "C-c C-M-l" #'org-toggle-link-display)
```
, then `prot-emacs-org.el` evals fine.

**Comment by protesilaos** [comment]
I am not sure how you get this error.  I search through all my dotfiles and these are the only matches for `org-mode-map`:

```
emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el
420:  (prot-emacs-keybind org-mode-map
emacs/.emacs.d/prot-emacs-modules/prot-emacs-write.el
106:    ;; shown here.  Otherwise follow the same pattern for `org-mode-map',
```

The second one is a comment, so it is irrelevant for our purposes.

Do you call `org-mode-map` somewhere in your files?  In that case, I can see the problem because Org has not been loaded yet.

**Comment by protesilaos** [comment]
Maybe this fixes the problem?

```diff
 emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el b/emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el
index 702fe96f..1bbee6c0 100644
--- a/emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el
+++ b/emacs/.emacs.d/prot-emacs-modules/prot-emacs-org.el
@@ -417,6 +417,9 @@ ;;;; Hooks and key bindings
     "C-c c" #'org-capture
     "C-c l" #'org-store-link
     "C-c o" #'org-open-at-point-global)
+
+  (require 'org)
+
   (prot-emacs-keybind org-mode-map
     ;; I don't like that Org binds one zillion keys, so if I want one
     ;; for something more important, I disable it from here.
```

**Comment by oneingan** [comment]
yep, it works!

**Comment by protesilaos** [comment]
I just pushed the change on my end.  Thank you!

* * *

By the way, I wanted to ask you about your notmuch setup with regard to filtering spam.  I believe you had told me about the use of the `spam` tag.  I am curious to learn what tools you use and how they work together.  You can email me about this, if you prefer.
